/* 1.	Realice una consulta que muestre todos los pacientes que tenga en el parámetro sexo una “M” 
        que significa Masculino, ordenado por el nombre del paciente.*/

SELECT * FROM PACIENTES WHERE SEXO='M' ORDER BY NOMBRE_PACIENTE

/*2.	Realice una consulta que me muestre solamente la cantidad de médicos que tienen una especialidad 
que en la descripción aparece como “MEDICINA GENERAL”.*/

SELECT COUNT(MED.CODIGO_MEDICO)CANTIDAD  FROM MEDICO MED
INNER JOIN ESPECIALIDAD  ESP ON ESP.CODIGO_ESPECIALIDAD=MED.CODIGO_ESPECIALIDAD
WHERE ESP.DESCRIPCION='MEDICINA GENERAL'

/* */
SELECT * FROM PACIENTES
SELECT * FROM CITAS_MEDICAS WHERE NOMBRE_PACIENTE LIKE 'JOSE ARMANDO%'

UPDATE CITAS_MEDICAS SET FECHA_CITA='2003-01-08' WHERE CEDULA='32226954'

UPDATE CI   SET  CI.FECHA_CITA='2003-01-08'
FROM CITAS_MEDICAS CI  
INNER JOIN  PACIENTES PA ON (CI.CEDULA=PA.CEDULA)
WHERE PA.NOMBRE_PACIENTE LIKE 'JOSE ARMANDO%'

SELECT *
FROM CITAS_MEDICAS CI  
INNER JOIN  PACIENTES PA ON (CI.CEDULA=PA.CEDULA)
WHERE PA.NOMBRE_PACIENTE LIKE 'JOSE ARMANDO%'


4.	Realice una consulta donde muestre el nombre del paciente, 
el nombre del médico que lo va a atender y la fecha de todos los pacientes.

SELECT PA.NOMBRE_PACIENTE,MED.NOMBRE_MEDICO,CITAS.FECHA_CITA FROM PACIENTES PA 
INNER JOIN CITAS_MEDICAS CITAS ON (CITAS.CEDULA=PA.CEDULA)
INNER JOIN MEDICO MED ON (MED.CODIGO_MEDICO=CITAS.CODIGO_MEDICO)

SELECT * FROM PACIENTES WHERE NOMBRE_PACIENTE LIKE 'JUA%'


6.	Se necesita tener la información de cuantos médicos hay por cada una de las especialidades
,  Ejemplo: Medicina General 25, optometría 10.

SELECT COUNT(MED.CODIGO_MEDICO) FROM MEDICO MED
INNER JOIN ESPECIALIDAD ESP ON (ESP.CODIGO_ESPECIALIDAD=MED.CODIGO_ESPECIALIDAD)
GROUP BY ESP.CODIGO_ESPECIALIDAD

SELECT * FROM CITAS_MEDICAS

SELECT * FROM MEDICO
SELECT * FROM ESPECIALIDAD